spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/splitease
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
jwt:
  secret: dGhpc2lzYXNlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbnRoYXRpc2xvbmdlbm91Z2g=
  expiration: 86400000